# Generated by Django 4.2.10 on 2024-02-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='topis',
            new_name='topics',
        ),
    ]
